
package com.realworldrobotics.hiegen.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigInteger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FormSessionPortType", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FormSessionPortType {


    /**
     * 
     * @param formEngineDescription
     * @param sessionIntentDescription
     * @param formPublisherDescription
     * @param sessionSet
     * @param sessionKey
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getSession")
    @RequestWrapper(localName = "getSession", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetSessionRequest")
    @ResponseWrapper(localName = "getSessionResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetSessionResponse")
    public void getSession(
        @WebParam(name = "formEngineDescription", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String formEngineDescription,
        @WebParam(name = "formPublisherDescription", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String formPublisherDescription,
        @WebParam(name = "sessionIntentDescription", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionIntentDescription,
        @WebParam(name = "sessionSet", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", mode = WebParam.Mode.OUT)
        Holder<Boolean> sessionSet,
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", mode = WebParam.Mode.OUT)
        Holder<String> sessionKey);

    /**
     * 
     * @param sessionKey
     * @return
     *     returns com.realworldrobotics.hiegen.wsdl.GetVersionResponse.Return
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getVersion")
    @WebResult(targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetVersionRequest")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetVersionResponse")
    public com.realworldrobotics.hiegen.wsdl.GetVersionResponse.Return getVersion(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey);

    /**
     * 
     * @param sessionKey
     * @return
     *     returns com.realworldrobotics.hiegen.wsdl.GetDeliveryOptionsResponse.Return
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getDeliveryOptions")
    @WebResult(targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "getDeliveryOptions", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetDeliveryOptionsRequest")
    @ResponseWrapper(localName = "getDeliveryOptionsResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetDeliveryOptionsResponse")
    public com.realworldrobotics.hiegen.wsdl.GetDeliveryOptionsResponse.Return getDeliveryOptions(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey);

    /**
     * 
     * @param patientSummaryList
     * @param patientSummaryCount
     * @param sessionKey
     * @param patientSearchSummary
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getPatient")
    @RequestWrapper(localName = "getPatient", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetPatientRequest")
    @ResponseWrapper(localName = "getPatientResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetPatientResponse")
    public void getPatient(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey,
        @WebParam(name = "patientSearchSummary", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        PatientSummary patientSearchSummary,
        @WebParam(name = "patientSummaryCount", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", mode = WebParam.Mode.OUT)
        Holder<BigInteger> patientSummaryCount,
        @WebParam(name = "patientSummaryList", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", mode = WebParam.Mode.OUT)
        Holder<PatientSummary> patientSummaryList);

    /**
     * 
     * @param patientId
     * @param patientIdType
     * @param currentUserPassword
     * @param currentUserId
     * @param currentUserName
     * @param sessionKey
     * @param currentUserIdType
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getSessionContext")
    @WebResult(name = "contextSet", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "getSessionContext", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetSessionContextRequest")
    @ResponseWrapper(localName = "getSessionContextResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetSessionContextResponse")
    public boolean getSessionContext(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey,
        @WebParam(name = "patientIdType", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String patientIdType,
        @WebParam(name = "patientId", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String patientId,
        @WebParam(name = "currentUserIdType", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String currentUserIdType,
        @WebParam(name = "currentUserId", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String currentUserId,
        @WebParam(name = "currentUserName", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String currentUserName,
        @WebParam(name = "currentUserPassword", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String currentUserPassword);

    /**
     * 
     * @param dataContainer
     * @param sessionKey
     * @return
     *     returns com.realworldrobotics.hiegen.wsdl.GetDataResponse.Return
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getData")
    @WebResult(targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "getData", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetDataRequest")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetDataResponse")
    public com.realworldrobotics.hiegen.wsdl.GetDataResponse.Return getData(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey,
        @WebParam(name = "dataContainer", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        FormData dataContainer);

    /**
     * 
     * @param continueSession
     * @param dataContainer
     * @param sessionKey
     * @param view
     * @param resumePath
     * @param viewType
     * @param viewSignature
     * @param completed
     * @return
     *     returns com.realworldrobotics.hiegen.wsdl.SaveContainerResponse.Return
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/saveContainer")
    @WebResult(targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "saveContainer", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.SaveContainerRequest")
    @ResponseWrapper(localName = "saveContainerResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.SaveContainerResponse")
    public com.realworldrobotics.hiegen.wsdl.SaveContainerResponse.Return saveContainer(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey,
        @WebParam(name = "resumePath", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String resumePath,
        @WebParam(name = "dataContainer", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        FormData dataContainer,
        @WebParam(name = "view", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String view,
        @WebParam(name = "viewType", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String viewType,
        @WebParam(name = "viewSignature", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String viewSignature,
        @WebParam(name = "completed", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        boolean completed,
        @WebParam(name = "continueSession", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        Boolean continueSession);

    /**
     * 
     * @param formInstanceId
     * @param sessionKey
     * @return
     *     returns com.realworldrobotics.hiegen.wsdl.GetFormViewResponse.Return
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/getFormView")
    @WebResult(targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "getFormView", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetFormViewRequest")
    @ResponseWrapper(localName = "getFormViewResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.GetFormViewResponse")
    public com.realworldrobotics.hiegen.wsdl.GetFormViewResponse.Return getFormView(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey,
        @WebParam(name = "formInstanceId", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String formInstanceId);

    /**
     * 
     * @param actionContainer
     * @param sessionKey
     * @param actionId
     * @return
     *     returns com.realworldrobotics.hiegen.wsdl.ProcessActionResponse.Return
     */
    @WebMethod(action = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/processAction")
    @WebResult(targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
    @RequestWrapper(localName = "processAction", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.ProcessActionRequest")
    @ResponseWrapper(localName = "processActionResponse", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession", className = "com.realworldrobotics.hiegen.wsdl.ProcessActionResponse")
    public com.realworldrobotics.hiegen.wsdl.ProcessActionResponse.Return processAction(
        @WebParam(name = "sessionKey", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String sessionKey,
        @WebParam(name = "actionId", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        String actionId,
        @WebParam(name = "actionContainer", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession")
        ActionContainer actionContainer);

}
