
package com.realworldrobotics.hiegen.wsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FormSessionService", targetNamespace = "http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/wsdl", wsdlLocation = "file:/F:/ODESK/CHANDAN/hiegen/WS_30_08/HieGenWS/src/wsdl/hieGenFormSession.wsdl")
public class FormSessionService
    extends Service
{

    private final static URL FORMSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException FORMSESSIONSERVICE_EXCEPTION;
    private final static QName FORMSESSIONSERVICE_QNAME = new QName("http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/wsdl", "FormSessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/ODESK/CHANDAN/hiegen/WS_30_08/HieGenWS/src/wsdl/hieGenFormSession.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMSESSIONSERVICE_WSDL_LOCATION = url;
        FORMSESSIONSERVICE_EXCEPTION = e;
    }

    public FormSessionService() {
        super(__getWsdlLocation(), FORMSESSIONSERVICE_QNAME);
    }

    public FormSessionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMSESSIONSERVICE_QNAME, features);
    }

    public FormSessionService(URL wsdlLocation) {
        super(wsdlLocation, FORMSESSIONSERVICE_QNAME);
    }

    public FormSessionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMSESSIONSERVICE_QNAME, features);
    }

    public FormSessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FormSessionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormSessionPortType
     */
    @WebEndpoint(name = "FormSessionPort")
    public FormSessionPortType getFormSessionPort() {
        return super.getPort(new QName("http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/wsdl", "FormSessionPort"), FormSessionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormSessionPortType
     */
    @WebEndpoint(name = "FormSessionPort")
    public FormSessionPortType getFormSessionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hiegen.realworldrobotics/hiegenforms/1.1/formsession/wsdl", "FormSessionPort"), FormSessionPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMSESSIONSERVICE_EXCEPTION!= null) {
            throw FORMSESSIONSERVICE_EXCEPTION;
        }
        return FORMSESSIONSERVICE_WSDL_LOCATION;
    }

}
