
package com.microsoft.schemas.ws._2008._06.identity.securitytokenservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.oasis_open.docs.ws_sx.ws_trust._200512.RequestSecurityTokenResponseCollectionType;
import org.oasis_open.docs.ws_sx.ws_trust._200512.RequestSecurityTokenType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWSTrust13Async", targetNamespace = "http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis_open.docs.ws_sx.ws_trust._200512.ObjectFactory.class,
    org.xmlsoap.schemas.ws._2005._02.trust.ObjectFactory.class,
    com.microsoft.schemas.message.ObjectFactory.class
})
public interface IWSTrust13Async {


    /**
     * 
     * @param request
     * @return
     *     returns org.oasis_open.docs.ws_sx.ws_trust._200512.RequestSecurityTokenResponseCollectionType
     */
    @WebMethod(operationName = "Trust13IssueAsync", action = "http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue")
    @WebResult(name = "RequestSecurityTokenResponseCollection", targetNamespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512", partName = "Trust13IssueAsyncResult")
    public RequestSecurityTokenResponseCollectionType trust13IssueAsync(
        @WebParam(name = "RequestSecurityToken", targetNamespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512", partName = "request")
        RequestSecurityTokenType request);

}
