
package com.upwork.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.accenture.nes.dto.webservicedto.ivr.ResetPinRequestDTO;
import com.accenture.nes.webservicedto.ivr.ResetPinResponseDTO;
import com.accenture.nes.webservices.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IIVRUserManagementService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
	com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class,
	com.accenture.nes.util.ObjectFactory.class,
	com.accenture.nes.webservicedto.ivr.ObjectFactory.class,
	com.accenture.nes.webservices.ObjectFactory.class
})
public interface IIVRUserManagementService {


	/**
	 * 
	 * @param authorizeUserRequestDTO
	 * @return
	 *     returns com.accenture.nes.webservicedto.ivr.AuthorizeUserResponseDTO
	 */
	@WebMethod(action = "urn:authorizeUser")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "authorizeUser", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.AuthorizeUser")
	@ResponseWrapper(localName = "authorizeUserResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.AuthorizeUserResponse")
	public AuthorizeUserResponseDTO authorizeUser(
			@WebParam(name = "Security", targetNamespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", 
			header = true, partName = "security") WsseSecurity securityHeader,
			@WebParam(name = "authorizeUserRequestDTO", targetNamespace = "")
			AuthorizeUserRequestDTO authorizeUserRequestDTO);

	/**
	 * 
	 * @param requestpinRequestDTO
	 * @return
	 *     returns com.accenture.nes.webservicedto.ivr.ResetPinResponseDTO
	 */
	@WebMethod(action = "urn:resetPIN")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "resetPIN", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.ResetPIN")
	@ResponseWrapper(localName = "resetPINResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.ResetPINResponse")
	public ResetPinResponseDTO resetPIN(
			@WebParam(name = "requestpinRequestDTO", targetNamespace = "")
			ResetPinRequestDTO requestpinRequestDTO);

}
