
package com.upwork.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IVRUserManagementService", targetNamespace = "http://webservices.nes.accenture.com", wsdlLocation = "file:/Users/daniyar/repos/chrome-extensions/upwork-jax-ws-client-new/src/main/resources/ivr/IVRUserManagementService.xml")
public class IVRUserManagementService
    extends Service
{

    private final static URL IVRUSERMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException IVRUSERMANAGEMENTSERVICE_EXCEPTION;
    private final static QName IVRUSERMANAGEMENTSERVICE_QNAME = new QName("http://webservices.nes.accenture.com", "IVRUserManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/daniyar/repos/chrome-extensions/upwork-jax-ws-client-new/src/main/resources/ivr/IVRUserManagementService.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IVRUSERMANAGEMENTSERVICE_WSDL_LOCATION = url;
        IVRUSERMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public IVRUserManagementService() {
        super(__getWsdlLocation(), IVRUSERMANAGEMENTSERVICE_QNAME);
    }

    public IVRUserManagementService(URL wsdlLocation) {
        super(wsdlLocation, IVRUSERMANAGEMENTSERVICE_QNAME);
    }

    public IVRUserManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IIVRUserManagementService
     */
    @WebEndpoint(name = "IVRUserManagementServiceImplPort")
    public IIVRUserManagementService getIVRUserManagementServiceImplPort() {
        return super.getPort(new QName("http://webservices.nes.accenture.com", "IVRUserManagementServiceImplPort"), IIVRUserManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IIVRUserManagementService
     */
    @WebEndpoint(name = "IVRUserManagementServiceImplPort")
    public IIVRUserManagementService getIVRUserManagementServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.nes.accenture.com", "IVRUserManagementServiceImplPort"), IIVRUserManagementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IVRUSERMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw IVRUSERMANAGEMENTSERVICE_EXCEPTION;
        }
        return IVRUSERMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
