
package com.upwork.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.xmlsoap.schemas.ws._2005._02.trust.RequestSecurityTokenResponseType;
import org.xmlsoap.schemas.ws._2005._02.trust.RequestSecurityTokenType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWSTrustFeb2005Async", targetNamespace = "http://schemas.microsoft.com/ws/2008/06/identity/securitytokenservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.upwork.test.ObjectFactory.class,
    org.xmlsoap.schemas.ws._2005._02.trust.ObjectFactory.class,
    com.microsoft.schemas.message.ObjectFactory.class
})
public interface IWSTrustFeb2005Async {


    /**
     * 
     * @param request
     * @return
     *     returns org.xmlsoap.schemas.ws._2005._02.trust.RequestSecurityTokenResponseType
     */
    @WebMethod(operationName = "TrustFeb2005IssueAsync", action = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue")
    @WebResult(name = "RequestSecurityTokenResponse", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust", partName = "TrustFeb2005IssueAsyncResult")
    public RequestSecurityTokenResponseType trustFeb2005IssueAsync(
        @WebParam(name = "RequestSecurityToken", targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/trust", partName = "request")
        RequestSecurityTokenType request);

}
