
package com.accenture.nes.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.accenture.nes.dto.webservicedto.ivr.GetPaymentStatusRequestDTO;
import com.accenture.nes.webservicedto.ivr.GetPaymentStatusResponceDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIVRPaymentDetailService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
    com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.webservices.ObjectFactory.class,
    com.accenture.nes.util.ObjectFactory.class,
    com.accenture.nes.webservicedto.ivr.ObjectFactory.class
})
public interface IIVRPaymentDetailService {


    /**
     * 
     * @param getPaymentStatusRequestDTO
     * @return
     *     returns com.accenture.nes.webservicedto.ivr.GetPaymentStatusResponceDTO
     */
    @WebMethod(operationName = "GetPaymentStatus", action = "GetPaymentStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetPaymentStatus", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetPaymentStatus")
    @ResponseWrapper(localName = "GetPaymentStatusResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetPaymentStatusResponse")
    public GetPaymentStatusResponceDTO getPaymentStatus(
        @WebParam(name = "getPaymentStatusRequestDTO", targetNamespace = "")
        GetPaymentStatusRequestDTO getPaymentStatusRequestDTO);

}
