
package com.accenture.nes.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.accenture.nes.dto.webservicedto.ivr.GetTaskDetailRequestDTO;
import com.accenture.nes.webservicedto.ivr.GetTaskDetailResponceDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIVRTaskManagementService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
    com.accenture.nes.webservices.ObjectFactory.class,
    com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.util.ObjectFactory.class,
    com.accenture.nes.webservicedto.ivr.ObjectFactory.class
})
public interface IIVRTaskManagementService {


    /**
     * 
     * @param getTaskDetailRequestDTO
     * @return
     *     returns com.accenture.nes.webservicedto.ivr.GetTaskDetailResponceDTO
     */
    @WebMethod(operationName = "GetTaskDetails", action = "urn:GetTaskDetails")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetTaskDetails", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetTaskDetails")
    @ResponseWrapper(localName = "GetTaskDetailsResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetTaskDetailsResponse")
    public GetTaskDetailResponceDTO getTaskDetails(
        @WebParam(name = "getTaskDetailRequestDTO", targetNamespace = "")
        GetTaskDetailRequestDTO getTaskDetailRequestDTO);

}
