
package com.accenture.nes.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.accenture.nes.dto.webservicedto.ivr.GetTicketStatusRequestDTO;
import com.accenture.nes.webservicedto.ivr.GetTicketStatusResponceDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIVRTicketManagementService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
    com.accenture.nes.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.util.ObjectFactory.class,
    com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.webservices.ObjectFactory.class
})
public interface IIVRTicketManagementService {


    /**
     * 
     * @param getTicketStatusRequestDTO
     * @return
     *     returns com.accenture.nes.webservicedto.ivr.GetTicketStatusResponceDTO
     */
    @WebMethod(action = "urn:getTicketStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketStatus", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetTicketStatus")
    @ResponseWrapper(localName = "getTicketStatusResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetTicketStatusResponse")
    public GetTicketStatusResponceDTO getTicketStatus(
        @WebParam(name = "getTicketStatusRequestDTO", targetNamespace = "")
        GetTicketStatusRequestDTO getTicketStatusRequestDTO);

}
