
package com.accenture.nes.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.accenture.nes.dto.webservicedto.ivr.ResetPasswordServiceRequestDTO;
import com.accenture.nes.dto.webservicedto.ivr.ResetPasswordServiceResponseDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIVRResetPasswordService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
    com.accenture.nes.util.ObjectFactory.class,
    com.accenture.nes.webservices.ObjectFactory.class,
    com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class
})
public interface IIVRResetPasswordService {


    /**
     * 
     * @param resetPasswordeReqDTO
     * @return
     *     returns com.accenture.nes.dto.webservicedto.ivr.ResetPasswordServiceResponseDTO
     * @throws EntityException_Exception
     */
    @WebMethod(action = "urn:resetPassword")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.ResetPasswordResponse")
    public ResetPasswordServiceResponseDTO resetPassword(
        @WebParam(name = "resetPasswordeReqDTO", targetNamespace = "")
        ResetPasswordServiceRequestDTO resetPasswordeReqDTO)
        throws EntityException_Exception
    ;

}
