
package com.accenture.nes.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.accenture.nes.dto.webservicedto.ivr.GetProgramStatusRequestDTO;
import com.accenture.nes.webservicedto.ivr.GetProgramStatusReponseDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIVRProgramManagementService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
    com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.webservices.ObjectFactory.class,
    com.accenture.nes.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.util.ObjectFactory.class
})
public interface IIVRProgramManagementService {


    /**
     * 
     * @param getProgramStatusRequestDTO
     * @return
     *     returns com.accenture.nes.webservicedto.ivr.GetProgramStatusReponseDTO
     */
    @WebMethod(action = "urn:getProgramStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProgramStatus", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetProgramStatus")
    @ResponseWrapper(localName = "getProgramStatusResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetProgramStatusResponse")
    public GetProgramStatusReponseDTO getProgramStatus(
        @WebParam(name = "getProgramStatusRequestDTO", targetNamespace = "")
        GetProgramStatusRequestDTO getProgramStatusRequestDTO);

}
