
package com.accenture.nes.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.accenture.nes.dto.webservicedto.ivr.GetJPCAttachmentDetailsRequestDTO;
import com.accenture.nes.webservicedto.ivr.GetJPCAttachmentDetailsResponseDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIVRJpcAttachmentService", targetNamespace = "http://webservices.nes.accenture.com/")
@XmlSeeAlso({
    com.accenture.nes.util.ObjectFactory.class,
    com.accenture.nes.dto.webservicedto.ivr.ObjectFactory.class,
    com.accenture.nes.webservices.ObjectFactory.class,
    com.accenture.nes.webservicedto.ivr.ObjectFactory.class
})
public interface IIVRJpcAttachmentService {


    /**
     * 
     * @param getJPCAttachmentDetailsRequestDTO
     * @return
     *     returns com.accenture.nes.webservicedto.ivr.GetJPCAttachmentDetailsResponseDTO
     */
    @WebMethod(action = "urn:getJPCAttachmentDetails")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJPCAttachmentDetails", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetJPCAttachmentDetails")
    @ResponseWrapper(localName = "getJPCAttachmentDetailsResponse", targetNamespace = "http://webservices.nes.accenture.com/", className = "com.accenture.nes.webservices.GetJPCAttachmentDetailsResponse")
    public GetJPCAttachmentDetailsResponseDTO getJPCAttachmentDetails(
        @WebParam(name = "getJPCAttachmentDetailsRequestDTO", targetNamespace = "")
        GetJPCAttachmentDetailsRequestDTO getJPCAttachmentDetailsRequestDTO);

}
